# Generated by Django 4.1.4 on 2023-01-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_alter_realtor_date_of_hire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='date_of_hire',
            new_name='hire_date',
        ),
    ]
